### ISSUE TITLE
dump parameter was removed in apispec 0.20

### ISSUE THREAD

**Issue by lafrech** [jmcarp/flask-apispec#41] opened 2017-03-20 08:42 UTC
This line

https://github.com/jmcarp/flask-apispec/blob/2f8429ca8e4fa4dd9c0dee12a721f2abd36a9778/flask_apispec/apidoc.py#L70

should be removed since that parameter was removed in apispec 0.20.0: https://github.com/marshmallow-code/apispec/commit/7009b17f4bc9c390427ebf51dd45f2fe41dfef8a.

See the change I made in flask-rest-api: https://github.com/Nobatek/flask-rest-api/commit/4a239d5adfd56a865c4d4901edbd3373a86a4470.

**Comment by rth** [comment] 2017-03-20 09:11
@lafrech Sounds reasonable. Are you sure this is still an issue with the current version on master? 

Your fork seems fairly outdated: e.g. `flask-apispec` minimal requirement for `apispec` is `>=0.4.1` while in your fork it's `apispec>=0.20.0`. It also has 40 less commits than master...

**Comment by lafrech** [comment] 2017-03-20 09:30
Not sure which fork you're talking about. We don't use flask-apispec, we use our own framework (flask-rest-api, the one I link to).

I think flask-apispec is broken if used with apispec 0.20.0. I contributed the change in apispec and it is a breaking change so I thought I'd stop by to tell you.

My suggestion is you do the same as I did in the flask-rest-api commit I pointed to:

- bump apispec requirement to 0.20.0
- remove dump parameter

Just a friendly hint. None of my business, actually.

**Comment by rth** [comment] 2017-03-20 09:33
Aww, right, my mistake, got confused by all the `flask-*` names. PRs to fix it, would be welcome ...

**Comment by rth** [comment] 2017-03-20 09:59
though raising the minimum requirement from apispec version >=0.4.1 (released 2015-10-20) to >=0.20.0 (released 2017-03-19) would be more problematic as it could break users code. It might be better to do some conditional code to support both versions. Thanks for opening this issue..

**Comment by Donal-Flanagan** [comment] 2017-03-22 10:20
Nice catch @lafrech. I just ran into this bug too. 
`TypeError: fields2parameters() got an unexpected keyword argument 'dump'`

**Comment by ffleandro** [comment] 2017-03-24 12:26
I'm experiencing this bug too.
Using `flask-apispec` from `master`, and `apispec 0.20.0`.

**Comment by rth** [comment] 2017-03-24 17:27
> I'm experiencing this bug too.

It's not a bug, it's a breaking change upstream.. ) Should be fixed with #45 .

**Comment by sloria** [comment] 2017-03-25 03:20
Fixed.

**Closed by sloria** 2017-03-25 03:20 UTC
